language: node_js
node_js:
- '10'
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn lint
- yarn cover
- yarn styleguide:build
notifications:
  slack:
    secure: VsE474aXVwiofaIwN5K4UUiK/F21ERz8I3/DsIYNlK0LttYblr9LRUXfmxhQSYy/7yceMRgK789qMC5w08yMgmjszlmti/PeDPQJIrgQMRTqxPGFoZvjyiFR8S0osjBr1iCK2TH46Z79kz/+AZObyPFsgRlxw/FpvbGs0HMvRvs8cDH5W+9uJmTeO5xlrAJwkQT+h3gQWF6ENSCiqirJDDo3a/sI9SckeQ7dL+hTIpUG+gsqQ94tI+9023jVoW+jrcF4UFzxILazq8O2seDId9W81iBfwshOisGOCAZOZ4QmX9pW9SM4eQ4jEigEmy6NknQq/ArrbIqVnzBlzdRZF2VTfL6ZJXPQv6MaRpJSaiqUn2seHiIfyM9YvIAcLvxP4TXHj6/43VaQ20ho/O+hRTarlRNRkKUbOQ+yyePthgW7GDiGT6hDY6cYqcBiVEpMOnW4+qYsCn4f6wypftwDVhv25ENZTGVhj1rQbPJtwe0NUIG+3eFqVAgn62YtbIAXERqyM/QXJZ72NE2fQqhpfWntnYmix0qKvRmRF4sfsPk6V77d19Eakvymp4nXVI9mnWM25qywVtu5sbOqzAgUKlai4lFj1MhkiXjMxNg/QtuT59DRvoJhTG2m4wpc0HMk2LRAX108ESF4QZD8R/UMy5HJHX4qPYypHMuj+OgEKNY=s
deploy:
  - provider: npm
    email: pia@istreamplanet.com
    api_key:
      secure: C9VeDTcOThMmoT03+Kyap1mtFwh1DA9DGcwoMyebDJgnTkqOf72+Kweh6T0hhCxOOrd9EB1dPEh4a3tSZeqK3sKRQl6ecbXq4PZnCmElp1nH0Pg33PzfDnAkgU9fLCortgZ1p5kwHKhFozgPcge+yMOyfX3ULuZUsqPWWEPQKk3/LMQghUu4zkmcQVBpiUXxZ2zvgu4uorAnHwO2+QHt6TCcIUcAW03Ti/Jr0cYGSjdHf+qQ/uxh+guPMdr72y0ndQ/ok8UsAl3pvMvRKHh/QRMgdpvTkLgFaPKku5s4xfae8cW/5/9LmpB9jDbLNxVunZfoZvoo7CtEMLNwvo0TOwVLF6bunSniFRpv1tfajHjl37G4iogvlTVQM+Gj8wmkoYJEiOw1ttwgPl3BRgJMs6tSlpXoESoDzZzIzWJcxJKHuexCwWCAAHm6BpWcSM2A7N8PHOmVtW/4dYevb5ha+T5cLur2pLvoCDKKMSOFx2iPh6BI9rl0sVcLfKB0hqU5E7HUwslGuJT/wHXJEZ0tUcjYNd5Lku0sDcvm03qns61EtAdxblk4eFGRFBuwthDo66boBQikZ7Fq8HHx0P1Wq5XWNcXx24mdieoSl8rwM92IVdPS9fluKZuKAekPSkeuEjWxq0k7blShwHFxzdx9RHq1Cfyb+7iFbPBKncv58w8=
    tag: next
    skip_cleanup: true
    on:
      tags: true
      repo: iStreamPlanet/pebble
