name: CI

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      CI: true
      CHROMATIC_APP_CODE: ${{ secrets.CHROMATIC_APP_CODE }}
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependencies
      run: yarn install
    - name: lint
      run: yarn lint
    - name: test with coverage
      run: |
        yarn cover
        curl -s https://codecov.io/bash | bash -s
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: yarn install
      - name: build styleguide
        run: yarn styleguide:build

