name: Chromatic visual validation
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'
jobs:
  chromatic:
    runs-on: ubuntu-latest
    env:
      env:
      CI: true
      CHROMATIC_APP_CODE: ${{ secrets.CHROMATIC_APP_CODE }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: yarn install
      - name: Run chromatic tests
        run: yarn chromatic --exit-zero-on-changes
