name: Pull Request on Branch Push
on:
  push:
    branches-ignore: [main]
jobs:
  auto-pull-request:
    name: Create a PR
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.0.11
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: main
          PULL_REQUEST_DRAFT: true
