name: deploy test site
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CI: true
      S3_PATH: pebble.istreamplanet.net/${{ github.event.number }}
      AWS_ACCESS_KEY_ID: ${{ secrets.DEVELOPMENT_AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEVELOPMENT_AWS_SECRET }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: yarn install
      - name: build styleguide
        run: yarn styleguide:build
      - name: deploy
        uses: actions/aws/cli@master
        with:
          args: ./deploy.sh $S3_PATH

