name: Pull Request
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CI: true
      AWS_ACCESS_KEY_ID: ${{ secrets.DEVELOPMENT_AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEVELOPMENT_AWS_SECRET }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: yarn install
      - name: build styleguide
        run: yarn styleguide:build
      - name: deploy js files
        uses: actions/aws/cli@master
        with:
          args: s3 sync styleguide s3://pebble.istreamplanet.net/${{ github.event.number }}/ --cache-control max-age=2592000 --exclude service-worker.js --exclude index.html
      - name: deploy service-worker.js
        uses: actions/aws/cli@master
        with:
          args: s3 cp styleguide/service-worker.js s3://pebble.istreamplanet.net/${{ github.event.number }}/service-worker.js --metadata-directive REPLACE --cache-control max-age=0,must-revalidate --content-type application/javascript
      - name: deploy index.html
        uses: actions/aws/cli@master
        with:
          args: s3 cp styleguide/index.html s3://pebble.istreamplanet.net/${{ github.event.number }}/index.html --metadata-directive REPLACE --cache-control max-age=0,must-revalidate --content-type text/html
      - name: link to PR
        run: echo "http://pebble.istreamplanet.net.s3-website-us-west-2.amazonaws.com/${{ github.event.number }}/index.html"
